// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropMan.Models;

#nullable disable

namespace PropMan.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251112092647_RemoveTenantId1")]
    partial class RemoveTenantId1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropMan.Models.AuditLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LogId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("PropMan.Models.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CompanyId");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("PropMan.Models.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastPaymentDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("PropertyTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InvoiceId")
                        .HasName("PK_ActiveInvoice");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PropertyTenantId");

                    b.ToTable("Invoice", (string)null);
                });

            modelBuilder.Entity("PropMan.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PropertyTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("SentTo")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PropertyTenantId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("PropMan.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PropertyTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PaymentId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PropertyTenantId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PropMan.Models.PaymentPlan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PlanId");

                    b.HasIndex("CompanyId");

                    b.ToTable("PaymentPlan", (string)null);
                });

            modelBuilder.Entity("PropMan.Models.Picture", b =>
                {
                    b.Property<Guid>("PictureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PictureId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Picture", (string)null);
                });

            modelBuilder.Entity("PropMan.Models.Property", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Cost Price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OccupancyStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OccuppiedUnits")
                        .HasColumnType("int");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SellingPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Selling Price");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("VacantUnits")
                        .HasColumnType("int");

                    b.HasKey("PropertyId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Property", (string)null);
                });

            modelBuilder.Entity("PropMan.Models.PropertyTenant", b =>
                {
                    b.Property<Guid>("PropertyTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AmountDue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("InitialDeposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimaryTenant")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastPaymentDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TenantId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("installmentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("totalInstallments")
                        .HasColumnType("int");

                    b.HasKey("PropertyTenantId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PlanId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId1")
                        .IsUnique()
                        .HasFilter("[TenantId1] IS NOT NULL");

                    b.HasIndex("UnitId");

                    b.ToTable("PropertyTenant", (string)null);
                });

            modelBuilder.Entity("PropMan.Models.PropertyUnit", b =>
                {
                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RentPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UnitId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyUnit", (string)null);
                });

            modelBuilder.Entity("PropMan.Models.Repair", b =>
                {
                    b.Property<Guid>("RepairId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("PropertyTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RepairId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PropertyTenantId");

                    b.ToTable("Repairs");
                });

            modelBuilder.Entity("PropMan.Models.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TenantId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Tenant", (string)null);
                });

            modelBuilder.Entity("PropMan.Models.TenantCredit", b =>
                {
                    b.Property<Guid>("TenantCreditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PropertyTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantCreditId");

                    b.HasIndex("PropertyTenantId");

                    b.ToTable("TenantCredits");
                });

            modelBuilder.Entity("PropMan.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("PropMan.Models.AuditLog", b =>
                {
                    b.HasOne("PropMan.Models.Company", "Company")
                        .WithMany("AuditLogs")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_AuditLog_Company");

                    b.HasOne("PropMan.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_AuditLog_User");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropMan.Models.Invoice", b =>
                {
                    b.HasOne("PropMan.Models.Company", "Company")
                        .WithMany("Invoices")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_ActiveInvoice_Company");

                    b.HasOne("PropMan.Models.PropertyTenant", "PropertyTenant")
                        .WithMany("Invoices")
                        .HasForeignKey("PropertyTenantId")
                        .IsRequired()
                        .HasConstraintName("FK_ActiveInvoice_PropertyTenant");

                    b.Navigation("Company");

                    b.Navigation("PropertyTenant");
                });

            modelBuilder.Entity("PropMan.Models.Notification", b =>
                {
                    b.HasOne("PropMan.Models.Company", "Company")
                        .WithMany("Notifications")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_Notification_Company");

                    b.HasOne("PropMan.Models.PropertyTenant", "PropertyTenant")
                        .WithMany("Notifications")
                        .HasForeignKey("PropertyTenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Notification_PropertyTenant");

                    b.Navigation("Company");

                    b.Navigation("PropertyTenant");
                });

            modelBuilder.Entity("PropMan.Models.Payment", b =>
                {
                    b.HasOne("PropMan.Models.Company", "Company")
                        .WithMany("Payments")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Company");

                    b.HasOne("PropMan.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_ActiveInvoice");

                    b.HasOne("PropMan.Models.PropertyTenant", "PropertyTenant")
                        .WithMany("Payments")
                        .HasForeignKey("PropertyTenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_PropertyTenant");

                    b.Navigation("Company");

                    b.Navigation("Invoice");

                    b.Navigation("PropertyTenant");
                });

            modelBuilder.Entity("PropMan.Models.PaymentPlan", b =>
                {
                    b.HasOne("PropMan.Models.Company", null)
                        .WithMany("PaymentPlans")
                        .HasForeignKey("CompanyId");
                });

            modelBuilder.Entity("PropMan.Models.Picture", b =>
                {
                    b.HasOne("PropMan.Models.Property", "Property")
                        .WithMany("Pictures")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK_Picture_Property");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropMan.Models.Property", b =>
                {
                    b.HasOne("PropMan.Models.Company", "Company")
                        .WithMany("Properties")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_Property_Company");

                    b.HasOne("PropMan.Models.User", "CreatedByNavigation")
                        .WithMany("Properties")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Property_User");

                    b.Navigation("Company");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("PropMan.Models.PropertyTenant", b =>
                {
                    b.HasOne("PropMan.Models.Company", "Company")
                        .WithMany("PropertyTenants")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_PropertyTenant_Company");

                    b.HasOne("PropMan.Models.PaymentPlan", "Plan")
                        .WithMany("PropertyTenants")
                        .HasForeignKey("PlanId")
                        .IsRequired()
                        .HasConstraintName("FK_PropertyTenant_PaymentPlan");

                    b.HasOne("PropMan.Models.Property", "Property")
                        .WithMany("PropertyTenants")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK_PropertyTenant_Property");

                    b.HasOne("PropMan.Models.Tenant", "Tenant")
                        .WithMany("PropertyTenants")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_PropertyTenant_Tenant");

                    b.HasOne("PropMan.Models.Tenant", null)
                        .WithOne("PropertyTenant")
                        .HasForeignKey("PropMan.Models.PropertyTenant", "TenantId1");

                    b.HasOne("PropMan.Models.PropertyUnit", "Unit")
                        .WithMany("PropertyTenants")
                        .HasForeignKey("UnitId")
                        .HasConstraintName("FK_PropertyTenant_PropertyUnit");

                    b.Navigation("Company");

                    b.Navigation("Plan");

                    b.Navigation("Property");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PropMan.Models.PropertyUnit", b =>
                {
                    b.HasOne("PropMan.Models.Company", "Company")
                        .WithMany("PropertyUnits")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_PropertyUnit_Company");

                    b.HasOne("PropMan.Models.Property", "Property")
                        .WithMany("PropertyUnits")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK_PropertyUnit_Property");

                    b.Navigation("Company");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropMan.Models.Repair", b =>
                {
                    b.HasOne("PropMan.Models.Company", "Company")
                        .WithMany("Repairs")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_Repairs_Company");

                    b.HasOne("PropMan.Models.PropertyTenant", "PropertyTenant")
                        .WithMany("Repairs")
                        .HasForeignKey("PropertyTenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Repairs_PropertyTenant");

                    b.Navigation("Company");

                    b.Navigation("PropertyTenant");
                });

            modelBuilder.Entity("PropMan.Models.Tenant", b =>
                {
                    b.HasOne("PropMan.Models.Company", "Company")
                        .WithMany("Tenants")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_Tenant_Company");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PropMan.Models.TenantCredit", b =>
                {
                    b.HasOne("PropMan.Models.PropertyTenant", "PropertyTenant")
                        .WithMany()
                        .HasForeignKey("PropertyTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyTenant");
                });

            modelBuilder.Entity("PropMan.Models.User", b =>
                {
                    b.HasOne("PropMan.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Company");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PropMan.Models.Company", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Invoices");

                    b.Navigation("Notifications");

                    b.Navigation("PaymentPlans");

                    b.Navigation("Payments");

                    b.Navigation("Properties");

                    b.Navigation("PropertyTenants");

                    b.Navigation("PropertyUnits");

                    b.Navigation("Repairs");

                    b.Navigation("Tenants");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PropMan.Models.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PropMan.Models.PaymentPlan", b =>
                {
                    b.Navigation("PropertyTenants");
                });

            modelBuilder.Entity("PropMan.Models.Property", b =>
                {
                    b.Navigation("Pictures");

                    b.Navigation("PropertyTenants");

                    b.Navigation("PropertyUnits");
                });

            modelBuilder.Entity("PropMan.Models.PropertyTenant", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("Repairs");
                });

            modelBuilder.Entity("PropMan.Models.PropertyUnit", b =>
                {
                    b.Navigation("PropertyTenants");
                });

            modelBuilder.Entity("PropMan.Models.Tenant", b =>
                {
                    b.Navigation("PropertyTenant")
                        .IsRequired();

                    b.Navigation("PropertyTenants");
                });

            modelBuilder.Entity("PropMan.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
